version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5420:5432
  

  vk-restapi:
    restart: on-failure
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=admin

